# Workflow for deploying RepoBee to PyPi

name: deploy

on:
  release:
    types: published

jobs:
  deploy-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Package RepoBee
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements/requirements.txt
        python -m pip install .
        python setup.py sdist bdist_wheel
    - name: Publish RepoBee to PyPi
      uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 # v1.8.14
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
