# Deployments to DockerHub

name: Deploy DockerHub

on:
  release:
    types: published
  push:
    branches: [ master ]

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    environment: DockerHub
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: repobee/repobee:test
      - name: Get RepoBee version
        id: get-repobee-version
        shell: bash
        run: |
          VERSION=v$(docker run -t repobee/repobee:test repobee --version)
          echo "::set-output name=version::$VERSION"
      - name: Build and push latest
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: repobee/repobee:latest
      - name: Build and push release
        uses: docker/build-push-action@v4
        if: ${{ github.event_name == 'release' }}
        with:
          context: .
          push: true
          tags: repobee/repobee:${{ steps.get-repobee-version.outputs.version }}
