# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:
      - "/^v\\d+\\.\\d+\\.\\d+(-(alpha|beta|rc)(\\.\\d+)?)?$/"
  schedule:
  - cron: "0 0 * * 6"

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9, '3.10', '3.11']
        core-commands-as-plugins: [false]
        exclude:
          - os: macos-latest
            python-version: 3.10
          - os: macos-latest
            python-version: 3.11
        include:
          - os: ubuntu-latest
            python-version: 3.9
            core-commands-as-plugins: true
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Git
      run: |
        git config --global user.name "Repo Bee"
        git config --global user.email repoobee@repobee.org
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install \
          -r requirements/requirements.txt \
          -r requirements/requirements.dev.txt
        pip install -e .[DEV]
    - name: Test with pytest
      env:
        REPOBEE_CORE_COMMANDS_AS_PLUGINS: ${{ matrix.core-commands-as-plugins }}
      run: |
        echo "REPOBEE_CORE_COMMANDS_AS_PLUGINS: $REPOBEE_CORE_COMMANDS_AS_PLUGINS"

        coverage run --branch \
            --source _repobee,repobee_plug,repobee_testhelpers \
            -m pytest tests/unit_tests tests/integration_tests
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
          fail_ci_if_error: false
          file: ./coverage.xml

  gitlab-system-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'create'
      || github.event_name == 'schedule'
      || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'gitlab')) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Set up Git
      run: |
        git config --global user.name "Repo Bee"
        git config --global user.email repoobee@repobee.org
        git config --global http.sslverify false
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install \
          -r requirements/requirements.txt \
          -r requirements/requirements.dev.txt
        pip install -e .[DEV]
    - name: Run system tests
      env:
        REPOBEE_NO_VERIFY_SSL: true
        PYTHONWARNINGS: "ignore:Unverified HTTPS request"
      run: |
        coverage run --branch \
            --source _repobee,repobee_plug,repobee_testhelpers \
            -m pytest system_tests/gitlab/test_gitlab_system.py -vv --showlocals
        coverage xml
    - name: Clean up volume data
      run: |
        sudo rm -rf system_tests/gitlab/volume_data
        git restore system_tests/gitlab/volume_data
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
          fail_ci_if_error: false
          file: ./coverage.xml

  gitea-system-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        core-commands-as-plugins: [false, true]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Set up Git
      run: |
        git config --global user.name "Repo Bee"
        git config --global user.email repoobee@repobee.org
    - name: Install RepoBee
      run: |
        python -m pip install --upgrade pip
        pip install \
          -r requirements/requirements.txt \
          -r requirements/requirements.dev.txt
        pip install -e .[DEV]
    - name: Run Gitea system tests
      env:
        REPOBEE_NO_VERIFY_SSL: true
        PYTHONWARNINGS: "ignore:Unverified HTTPS request"
        REPOBEE_CORE_COMMANDS_AS_PLUGINS: ${{ matrix.core-commands-as-plugins }}
      run: |
        echo "REPOBEE_CORE_COMMANDS_AS_PLUGINS: $REPOBEE_CORE_COMMANDS_AS_PLUGINS"

        git config --global http.sslverify false
        python system_tests/gitea/giteamanager.py prime
        coverage run --branch \
            --source _repobee,repobee_plug,repobee_testhelpers \
            -m pytest -vv --showlocals system_tests/gitea
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
          fail_ci_if_error: false
          file: ./coverage.xml
