# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:
      - "/^v\\d+\\.\\d+\\.\\d+(-(alpha|beta|rc)(\\.\\d+)?)?$/"
  schedule:
  - cron: "0 0 * * *"

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        exclude:
          - os: macos-latest
            python-version: 3.7
          - os: macos-latest
            python-version: 3.8
          - os: macos-latest
            python-version: 3.9
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Git
      run: |
        git config --global user.name "Repo Bee"
        git config --global user.email repoobee@repobee.org
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt
        pip install -e .[TEST]
    - name: Test with pytest
      run: |
        coverage run --branch \
            --source _repobee,repobee_plug,repobee_testhelpers \
            -m pytest tests/unit_tests tests/new_integration_tests
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
          fail_ci_if_error: true
          file: ./coverage.xml

  gitlab-system-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'create' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'gitlab')) }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Build RepoBee container
      run: docker build -t repobee:test -f Dockerfile.test .
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install RepoBee
      run: pip install -e .[TEST]
    - name: Run system tests
      env:
        REPOBEE_NO_VERIFY_SSL: true
        PYTHONWARNINGS: "ignore:Unverified HTTPS request"
      run: |
        pytest system_tests/gitlab/test_gitlab_system.py -vv --showlocals
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
          fail_ci_if_error: true
          file: ./.coverage_files/coverage.xml

  gitea-system-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Set up Git
      run: |
        git config --global user.name "Repo Bee"
        git config --global user.email repoobee@repobee.org
    - name: Install RepoBee
      run: pip install -e .[TEST]
    - name: Run Gitea system tests
      env:
        REPOBEE_NO_VERIFY_SSL: true
        PYTHONWARNINGS: "ignore:Unverified HTTPS request"
      run: |
        git config --global http.sslverify false
        python system_tests/gitea/giteamanager.py prime
        coverage run --branch \
            --source _repobee,repobee_plug,repobee_testhelpers \
            -m pytest -vv --showlocals system_tests/gitea
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
          fail_ci_if_error: true
          file: ./coverage.xml
